# Generated by Django 6.0.4 on 2026-06-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_initial'),
        ('services', '0002_alter_service_options_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='services.service'),
        ),
    ]
