# Generated by Django 6.0.4 on 2026-05-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('duration_months', models.IntegerField(default=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AMC Plan',
                'verbose_name_plural': 'AMC Plans',
            },
        ),
        migrations.CreateModel(
            name='AMCService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_per_year', models.IntegerField(default=2, help_text='Number of service visits per year')),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='amc.amcplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_plans', to='services.service')),
            ],
            options={
                'verbose_name': 'AMC Service',
                'verbose_name_plural': 'AMC Services',
            },
        ),
        migrations.CreateModel(
            name='CustomerAMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to='amc.amcplan')),
            ],
            options={
                'verbose_name': 'Customer AMC',
                'verbose_name_plural': 'Customer AMCs',
            },
        ),
    ]
