# Generated by Django 6.0.4 on 2026-05-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amc', '0001_initial'),
        ('assets', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeramc',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amcs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_amcs', to='tenants.branch'),
        ),
    ]
