# Generated by Django 6.0.4 on 2026-05-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_initial'),
        ('customers', '0004_customeraddress_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeramc',
            name='custom_visits_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amcs', to='customers.customeraddress'),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='visit_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='quarterly', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeramc',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending_approval', 'Pending Approval')], default='active', max_length=20),
        ),
    ]
