# Generated by Django 6.0.4 on 2026-05-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_customeramc_custom_visits_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeramc',
            name='manual_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='manual_plan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='manual_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeramc',
            name='amc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_subscriptions', to='amc.amcplan'),
        ),
    ]
