# Generated by Django 6.0.4 on 2026-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_customeramc_manual_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeramc',
            name='completed_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='total_visits',
            field=models.IntegerField(default=4),
        ),
    ]
