# Generated by Django 6.0.4 on 2026-05-26 11:12

from django.db import migrations


def repair_customer_table(apps, schema_editor):
    table_name = 'customers_customer'
    connection = schema_editor.connection

    existing_tables = set(connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

    if 'id' in columns and 'customer_id' not in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} RENAME COLUMN id TO customer_id'
        )
        columns.remove('id')
        columns.add('customer_id')

    if 'alternate_mobile_num' not in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} ADD COLUMN alternate_mobile_num varchar(20) NULL'
        )

    if 'billing_address' not in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} ADD COLUMN billing_address text NULL'
        )


def reverse_repair_customer_table(apps, schema_editor):
    table_name = 'customers_customer'
    connection = schema_editor.connection

    existing_tables = set(connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

    if 'customer_id' in columns and 'id' not in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} RENAME COLUMN customer_id TO id'
        )

    if 'alternate_mobile_num' in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} DROP COLUMN alternate_mobile_num'
        )

    if 'billing_address' in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} DROP COLUMN billing_address'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(repair_customer_table, reverse_repair_customer_table),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='customer',
                    name='billing_city',
                ),
                migrations.RemoveField(
                    model_name='customer',
                    name='billing_pincode',
                ),
                migrations.RemoveField(
                    model_name='customer',
                    name='billing_state',
                ),
            ],
        ),
    ]
