# Generated by Django 6.0.4 on 2026-05-26 12:38

from django.db import migrations, models


def repair_customer_address_table(apps, schema_editor):
    table_name = 'customers_customeraddress'
    connection = schema_editor.connection

    CustomerAddress = apps.get_model('customers', 'CustomerAddress')
    existing_tables = set(connection.introspection.table_names())

    if table_name not in existing_tables:
        schema_editor.create_model(CustomerAddress)
        return


def reverse_repair_customer_address_table(apps, schema_editor):
    table_name = 'customers_customeraddress'
    connection = schema_editor.connection

    existing_tables = set(connection.introspection.table_names())
    if table_name not in existing_tables:
        return


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_billing_city_and_more'),
    ]

    operations = [
        migrations.RunPython(repair_customer_address_table, reverse_repair_customer_address_table),
        migrations.AddField(
            model_name='customeraddress',
            name='customer_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
    ]
