# Generated by Django 6.0.4 on 2026-05-27

from django.db import migrations


def add_is_active_column(apps, schema_editor):
    table_name = 'customers_customer'
    connection = schema_editor.connection

    existing_tables = set(connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

    if 'is_active' not in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} ADD COLUMN is_active boolean NOT NULL DEFAULT true'
        )


def remove_is_active_column(apps, schema_editor):
    table_name = 'customers_customer'
    connection = schema_editor.connection

    existing_tables = set(connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

    if 'is_active' in columns:
        schema_editor.execute(
            f'ALTER TABLE {table_name} DROP COLUMN is_active'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customeraddress_customer_type'),
    ]

    operations = [
        migrations.RunPython(add_is_active_column, remove_is_active_column),
    ]