# Generated by Django 6.0.4 on 2026-06-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_customer_is_active'),
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.customeraddress'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('diagnosis_completed', 'Diagnosis Completed'), ('quotation_pending', 'Quotation Pending'), ('quotation_approved', 'Quotation Approved'), ('work_in_progress', 'Work In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
