# Generated by Django 6.0.4 on 2026-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('amc', 'AMC'), ('installation', 'Installation'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
