# Generated by Django 6.0.4 on 2026-05-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
        ('customers', '0004_customeraddress_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customeraddress'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('technician_on_the_way', 'Technician On The Way'), ('in_progress', 'In Progress'), ('parts_pending', 'Parts Pending'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='open', max_length=25),
        ),
    ]
