# Generated by Django 6.0.4 on 2026-05-26 11:07

import apps.users.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('mobile_num', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, choices=[('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('TECHNICIAN', 'Technician')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL for superusers (Platform Admin). Required for tenant users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_users', related_query_name='branch_user', to='tenants.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL for superusers (Platform Admin). Auto-derived from branch for regular users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'ordering': ['tenant_id', 'branch_id', 'role', 'email_id'],
                'indexes': [models.Index(fields=['tenant', 'branch', 'role'], name='users_user_tenant__a64bf4_idx'), models.Index(fields=['email_id'], name='users_user_email_i_1d7c9c_idx')],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
