# Generated by Django 6.0.4 on 2026-05-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('customers', '0004_customeraddress_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customers.customeraddress'),
        ),
    ]
